name: chat_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.2
  rxdart: ^0.21.0
  image_picker: ^0.8.4+10
  flutter_screenutil: ^5.3.1
  fancy_bottom_navigation: ^0.3.3
  font_awesome_flutter: ^9.2.0
  skeleton_loader: ^2.0.0+4
  json_serializable: ^6.1.5
  equatable: ^2.0.3
  http: ^0.13.4
  connectivity_plus: ^2.2.1
  socket_io_client: ^1.0.2
  tuple: ^2.0.0
  flutter_chat_ui: ^1.5.7
  open_file: ^3.2.1
  file_picker: ^4.5.1
  uuid: ^3.0.6
  day_night_switcher: ^0.2.0+1
  flutter_bloc: ^8.0.1
  localstorage: ^4.0.0+1
  localstore: ^1.2.3
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.0.0
  flutter_webrtc: ^0.8.9
  flutter_downloader: ^1.7.4
  android_path_provider: ^0.3.0
  agora_uikit: ^1.0.1
  agora_rtm: ^1.1.1
  external_app_launcher: ^2.0.2
  change_app_package_name: ^1.1.0
  package_info_plus: ^1.4.2
  device_apps: ^2.2.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/messages.json
    - assets/user.json
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
