const NUMBER_ROOM_PER_LOAD = 10;
const NUMBER_MESSAGE_PER_LOAD = 10;
const NUMBER_ACTIVE_UER_PER_LOAD = 10;

export {
    NUMBER_ROOM_PER_LOAD,
    NUMBER_MESSAGE_PER_LOAD,
    NUMBER_ACTIVE_UER_PER_LOAD,
};
