const NUMBER_ROOM_PER_LOAD = 10;
const NUMBER_MESSAGE_PER_LOAD = 10;
const NUMBER_ACTIVE_UER_PER_LOAD = 10;
const MAX_FILE_NUMBER_RECEIVE = 10;

const INVALID_INPUT_MESSAGE='Invalid input';

const ROOM_UPLOAD_DIR = 'public/room/';
const CHAT_UPLOAD_DIR = 'public/message/'

export {
    NUMBER_ROOM_PER_LOAD,
    NUMBER_MESSAGE_PER_LOAD,
    NUMBER_ACTIVE_UER_PER_LOAD,
    INVALID_INPUT_MESSAGE,
    ROOM_UPLOAD_DIR,
    CHAT_UPLOAD_DIR,
    MAX_FILE_NUMBER_RECEIVE
};
